export const FETCH_JOKES = 'a vicious karate chop to the neck'
export const CREATE_ENTRY = 'a round-house kick to the ribs measured at 96mph'
export const DELETE_ENTRY = 'crounching tigger, hidden dragon'
export const SET_SEARCH_FILTER = 'the fist within the beard'
export const SET_SORT_BY_FILTER = 'blackbelt degrees higher than the sun'
export const USER_SEARCH_QUERY = 'chuck norris can delete the recycling bin'
